---
services:
  # pogo:
  #   build:
  #     context: .
  #     dockerfile: Dockerfile
  #   depends_on:
  #     - db
  #   ports:
  #     - 4321:4321
  #     - 6060:6060
  #   environment:
  #     - PORT=4321
  #     - DATABASE_URL=postgres://pogo:pogo@db:5432/pogo
  #   volumes:
  #     - ./pogo_data/:/pogo/
  db:
    image: postgres:17-alpine
    environment:
      - POSTGRES_USER=pogo
      - POSTGRES_PASSWORD=pogo
      - POSTGRES_DB=pogo
    ports:
      - 5432:5432
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U pogo"]
      interval: 10s
      timeout: 5s
      retries: 5
