// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: protos/messages.proto

package protos

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type HTTPSignature struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The signed data
	BodyHash    []byte                 `protobuf:"bytes,1,opt,name=body_hash,json=bodyHash,proto3" json:"body_hash,omitempty"`
	RequestPath string                 `protobuf:"bytes,2,opt,name=request_path,json=requestPath,proto3" json:"request_path,omitempty"`
	Timestamp   *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Username    string                 `protobuf:"bytes,4,opt,name=username,proto3" json:"username,omitempty"`
	MachineId   string                 `protobuf:"bytes,5,opt,name=machine_id,json=machineId,proto3" json:"machine_id,omitempty"`
	PublicKey   []byte                 `protobuf:"bytes,6,opt,name=public_key,json=publicKey,proto3" json:"public_key,omitempty"`
	// The signature
	Format        string `protobuf:"bytes,7,opt,name=format,proto3" json:"format,omitempty"`
	Blob          []byte `protobuf:"bytes,8,opt,name=blob,proto3" json:"blob,omitempty"`
	Rest          []byte `protobuf:"bytes,9,opt,name=rest,proto3" json:"rest,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HTTPSignature) Reset() {
	*x = HTTPSignature{}
	mi := &file_protos_messages_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HTTPSignature) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HTTPSignature) ProtoMessage() {}

func (x *HTTPSignature) ProtoReflect() protoreflect.Message {
	mi := &file_protos_messages_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HTTPSignature.ProtoReflect.Descriptor instead.
func (*HTTPSignature) Descriptor() ([]byte, []int) {
	return file_protos_messages_proto_rawDescGZIP(), []int{0}
}

func (x *HTTPSignature) GetBodyHash() []byte {
	if x != nil {
		return x.BodyHash
	}
	return nil
}

func (x *HTTPSignature) GetRequestPath() string {
	if x != nil {
		return x.RequestPath
	}
	return ""
}

func (x *HTTPSignature) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

func (x *HTTPSignature) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *HTTPSignature) GetMachineId() string {
	if x != nil {
		return x.MachineId
	}
	return ""
}

func (x *HTTPSignature) GetPublicKey() []byte {
	if x != nil {
		return x.PublicKey
	}
	return nil
}

func (x *HTTPSignature) GetFormat() string {
	if x != nil {
		return x.Format
	}
	return ""
}

func (x *HTTPSignature) GetBlob() []byte {
	if x != nil {
		return x.Blob
	}
	return nil
}

func (x *HTTPSignature) GetRest() []byte {
	if x != nil {
		return x.Rest
	}
	return nil
}

type InitRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=Name,proto3" json:"Name,omitempty"`
	Bookmarks     []string               `protobuf:"bytes,2,rep,name=Bookmarks,proto3" json:"Bookmarks,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InitRequest) Reset() {
	*x = InitRequest{}
	mi := &file_protos_messages_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InitRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InitRequest) ProtoMessage() {}

func (x *InitRequest) ProtoReflect() protoreflect.Message {
	mi := &file_protos_messages_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InitRequest.ProtoReflect.Descriptor instead.
func (*InitRequest) Descriptor() ([]byte, []int) {
	return file_protos_messages_proto_rawDescGZIP(), []int{1}
}

func (x *InitRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *InitRequest) GetBookmarks() []string {
	if x != nil {
		return x.Bookmarks
	}
	return nil
}

type InitResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RepoID        int32                  `protobuf:"varint,1,opt,name=RepoID,proto3" json:"RepoID,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InitResponse) Reset() {
	*x = InitResponse{}
	mi := &file_protos_messages_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InitResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InitResponse) ProtoMessage() {}

func (x *InitResponse) ProtoReflect() protoreflect.Message {
	mi := &file_protos_messages_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InitResponse.ProtoReflect.Descriptor instead.
func (*InitResponse) Descriptor() ([]byte, []int) {
	return file_protos_messages_proto_rawDescGZIP(), []int{2}
}

func (x *InitResponse) GetRepoID() int32 {
	if x != nil {
		return x.RepoID
	}
	return 0
}

type PushFileInfo struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Name            string                 `protobuf:"bytes,1,opt,name=Name,proto3" json:"Name,omitempty"`
	Executable      *bool                  `protobuf:"varint,2,opt,name=Executable,proto3,oneof" json:"Executable,omitempty"`
	ContentHash     []byte                 `protobuf:"bytes,3,opt,name=ContentHash,proto3" json:"ContentHash,omitempty"`
	ContainsContent bool                   `protobuf:"varint,4,opt,name=ContainsContent,proto3" json:"ContainsContent,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *PushFileInfo) Reset() {
	*x = PushFileInfo{}
	mi := &file_protos_messages_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PushFileInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PushFileInfo) ProtoMessage() {}

func (x *PushFileInfo) ProtoReflect() protoreflect.Message {
	mi := &file_protos_messages_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PushFileInfo.ProtoReflect.Descriptor instead.
func (*PushFileInfo) Descriptor() ([]byte, []int) {
	return file_protos_messages_proto_rawDescGZIP(), []int{3}
}

func (x *PushFileInfo) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *PushFileInfo) GetExecutable() bool {
	if x != nil && x.Executable != nil {
		return *x.Executable
	}
	return false
}

func (x *PushFileInfo) GetContentHash() []byte {
	if x != nil {
		return x.ContentHash
	}
	return nil
}

func (x *PushFileInfo) GetContainsContent() bool {
	if x != nil {
		return x.ContainsContent
	}
	return false
}

type CheckFilesExistsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ContentHash   [][]byte               `protobuf:"bytes,1,rep,name=ContentHash,proto3" json:"ContentHash,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CheckFilesExistsRequest) Reset() {
	*x = CheckFilesExistsRequest{}
	mi := &file_protos_messages_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckFilesExistsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckFilesExistsRequest) ProtoMessage() {}

func (x *CheckFilesExistsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_protos_messages_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckFilesExistsRequest.ProtoReflect.Descriptor instead.
func (*CheckFilesExistsRequest) Descriptor() ([]byte, []int) {
	return file_protos_messages_proto_rawDescGZIP(), []int{4}
}

func (x *CheckFilesExistsRequest) GetContentHash() [][]byte {
	if x != nil {
		return x.ContentHash
	}
	return nil
}

type CheckFilesExistsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Exists        []bool                 `protobuf:"varint,1,rep,packed,name=Exists,proto3" json:"Exists,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CheckFilesExistsResponse) Reset() {
	*x = CheckFilesExistsResponse{}
	mi := &file_protos_messages_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckFilesExistsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckFilesExistsResponse) ProtoMessage() {}

func (x *CheckFilesExistsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_protos_messages_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckFilesExistsResponse.ProtoReflect.Descriptor instead.
func (*CheckFilesExistsResponse) Descriptor() ([]byte, []int) {
	return file_protos_messages_proto_rawDescGZIP(), []int{5}
}

func (x *CheckFilesExistsResponse) GetExists() []bool {
	if x != nil {
		return x.Exists
	}
	return nil
}

type NewChangeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Parents       []string               `protobuf:"bytes,1,rep,name=Parents,proto3" json:"Parents,omitempty"`
	Description   *string                `protobuf:"bytes,2,opt,name=description,proto3,oneof" json:"description,omitempty"`
	SetBookmarks  []string               `protobuf:"bytes,3,rep,name=SetBookmarks,proto3" json:"SetBookmarks,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NewChangeRequest) Reset() {
	*x = NewChangeRequest{}
	mi := &file_protos_messages_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NewChangeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NewChangeRequest) ProtoMessage() {}

func (x *NewChangeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_protos_messages_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NewChangeRequest.ProtoReflect.Descriptor instead.
func (*NewChangeRequest) Descriptor() ([]byte, []int) {
	return file_protos_messages_proto_rawDescGZIP(), []int{6}
}

func (x *NewChangeRequest) GetParents() []string {
	if x != nil {
		return x.Parents
	}
	return nil
}

func (x *NewChangeRequest) GetDescription() string {
	if x != nil && x.Description != nil {
		return *x.Description
	}
	return ""
}

func (x *NewChangeRequest) GetSetBookmarks() []string {
	if x != nil {
		return x.SetBookmarks
	}
	return nil
}

type SetBookmarkRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Bookmark      string                 `protobuf:"bytes,1,opt,name=Bookmark,proto3" json:"Bookmark,omitempty"`
	ChangeId      int64                  `protobuf:"varint,2,opt,name=ChangeId,proto3" json:"ChangeId,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetBookmarkRequest) Reset() {
	*x = SetBookmarkRequest{}
	mi := &file_protos_messages_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetBookmarkRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetBookmarkRequest) ProtoMessage() {}

func (x *SetBookmarkRequest) ProtoReflect() protoreflect.Message {
	mi := &file_protos_messages_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetBookmarkRequest.ProtoReflect.Descriptor instead.
func (*SetBookmarkRequest) Descriptor() ([]byte, []int) {
	return file_protos_messages_proto_rawDescGZIP(), []int{7}
}

func (x *SetBookmarkRequest) GetBookmark() string {
	if x != nil {
		return x.Bookmark
	}
	return ""
}

func (x *SetBookmarkRequest) GetChangeId() int64 {
	if x != nil {
		return x.ChangeId
	}
	return 0
}

type NewChangeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ChangeId      int64                  `protobuf:"varint,1,opt,name=ChangeId,proto3" json:"ChangeId,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NewChangeResponse) Reset() {
	*x = NewChangeResponse{}
	mi := &file_protos_messages_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NewChangeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NewChangeResponse) ProtoMessage() {}

func (x *NewChangeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_protos_messages_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NewChangeResponse.ProtoReflect.Descriptor instead.
func (*NewChangeResponse) Descriptor() ([]byte, []int) {
	return file_protos_messages_proto_rawDescGZIP(), []int{8}
}

func (x *NewChangeResponse) GetChangeId() int64 {
	if x != nil {
		return x.ChangeId
	}
	return 0
}

type CheckoutRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ChangeId      int64                  `protobuf:"varint,1,opt,name=ChangeId,proto3" json:"ChangeId,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CheckoutRequest) Reset() {
	*x = CheckoutRequest{}
	mi := &file_protos_messages_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckoutRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckoutRequest) ProtoMessage() {}

func (x *CheckoutRequest) ProtoReflect() protoreflect.Message {
	mi := &file_protos_messages_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckoutRequest.ProtoReflect.Descriptor instead.
func (*CheckoutRequest) Descriptor() ([]byte, []int) {
	return file_protos_messages_proto_rawDescGZIP(), []int{9}
}

func (x *CheckoutRequest) GetChangeId() int64 {
	if x != nil {
		return x.ChangeId
	}
	return 0
}

type LogRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Head          string                 `protobuf:"bytes,1,opt,name=Head,proto3" json:"Head,omitempty"`
	Limit         int32                  `protobuf:"varint,2,opt,name=Limit,proto3" json:"Limit,omitempty"`
	TimeZone      string                 `protobuf:"bytes,3,opt,name=TimeZone,proto3" json:"TimeZone,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LogRequest) Reset() {
	*x = LogRequest{}
	mi := &file_protos_messages_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LogRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogRequest) ProtoMessage() {}

func (x *LogRequest) ProtoReflect() protoreflect.Message {
	mi := &file_protos_messages_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LogRequest.ProtoReflect.Descriptor instead.
func (*LogRequest) Descriptor() ([]byte, []int) {
	return file_protos_messages_proto_rawDescGZIP(), []int{10}
}

func (x *LogRequest) GetHead() string {
	if x != nil {
		return x.Head
	}
	return ""
}

func (x *LogRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *LogRequest) GetTimeZone() string {
	if x != nil {
		return x.TimeZone
	}
	return ""
}

type LogResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Log           string                 `protobuf:"bytes,1,opt,name=Log,proto3" json:"Log,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LogResponse) Reset() {
	*x = LogResponse{}
	mi := &file_protos_messages_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LogResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogResponse) ProtoMessage() {}

func (x *LogResponse) ProtoReflect() protoreflect.Message {
	mi := &file_protos_messages_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LogResponse.ProtoReflect.Descriptor instead.
func (*LogResponse) Descriptor() ([]byte, []int) {
	return file_protos_messages_proto_rawDescGZIP(), []int{11}
}

func (x *LogResponse) GetLog() string {
	if x != nil {
		return x.Log
	}
	return ""
}

type FindChangeRequest struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	Name               string                 `protobuf:"bytes,1,opt,name=Name,proto3" json:"Name,omitempty"`
	IncludeDescription bool                   `protobuf:"varint,2,opt,name=IncludeDescription,proto3" json:"IncludeDescription,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *FindChangeRequest) Reset() {
	*x = FindChangeRequest{}
	mi := &file_protos_messages_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FindChangeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FindChangeRequest) ProtoMessage() {}

func (x *FindChangeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_protos_messages_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FindChangeRequest.ProtoReflect.Descriptor instead.
func (*FindChangeRequest) Descriptor() ([]byte, []int) {
	return file_protos_messages_proto_rawDescGZIP(), []int{12}
}

func (x *FindChangeRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *FindChangeRequest) GetIncludeDescription() bool {
	if x != nil {
		return x.IncludeDescription
	}
	return false
}

type FindChangeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ChangeId      int64                  `protobuf:"varint,1,opt,name=ChangeId,proto3" json:"ChangeId,omitempty"`
	Description   *string                `protobuf:"bytes,2,opt,name=Description,proto3,oneof" json:"Description,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FindChangeResponse) Reset() {
	*x = FindChangeResponse{}
	mi := &file_protos_messages_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FindChangeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FindChangeResponse) ProtoMessage() {}

func (x *FindChangeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_protos_messages_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FindChangeResponse.ProtoReflect.Descriptor instead.
func (*FindChangeResponse) Descriptor() ([]byte, []int) {
	return file_protos_messages_proto_rawDescGZIP(), []int{13}
}

func (x *FindChangeResponse) GetChangeId() int64 {
	if x != nil {
		return x.ChangeId
	}
	return 0
}

func (x *FindChangeResponse) GetDescription() string {
	if x != nil && x.Description != nil {
		return *x.Description
	}
	return ""
}

type DescribeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Change        string                 `protobuf:"bytes,1,opt,name=Change,proto3" json:"Change,omitempty"`
	Description   string                 `protobuf:"bytes,2,opt,name=Description,proto3" json:"Description,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DescribeRequest) Reset() {
	*x = DescribeRequest{}
	mi := &file_protos_messages_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DescribeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DescribeRequest) ProtoMessage() {}

func (x *DescribeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_protos_messages_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DescribeRequest.ProtoReflect.Descriptor instead.
func (*DescribeRequest) Descriptor() ([]byte, []int) {
	return file_protos_messages_proto_rawDescGZIP(), []int{14}
}

func (x *DescribeRequest) GetChange() string {
	if x != nil {
		return x.Change
	}
	return ""
}

func (x *DescribeRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

type ListBookmarksResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Bookmarks     []*Bookmark            `protobuf:"bytes,1,rep,name=Bookmarks,proto3" json:"Bookmarks,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListBookmarksResponse) Reset() {
	*x = ListBookmarksResponse{}
	mi := &file_protos_messages_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListBookmarksResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListBookmarksResponse) ProtoMessage() {}

func (x *ListBookmarksResponse) ProtoReflect() protoreflect.Message {
	mi := &file_protos_messages_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListBookmarksResponse.ProtoReflect.Descriptor instead.
func (*ListBookmarksResponse) Descriptor() ([]byte, []int) {
	return file_protos_messages_proto_rawDescGZIP(), []int{15}
}

func (x *ListBookmarksResponse) GetBookmarks() []*Bookmark {
	if x != nil {
		return x.Bookmarks
	}
	return nil
}

type Bookmark struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BookmarkName  string                 `protobuf:"bytes,1,opt,name=BookmarkName,proto3" json:"BookmarkName,omitempty"`
	ChangeID      int64                  `protobuf:"varint,2,opt,name=ChangeID,proto3" json:"ChangeID,omitempty"`
	ChangeName    string                 `protobuf:"bytes,3,opt,name=ChangeName,proto3" json:"ChangeName,omitempty"`
	ChangePrefix  string                 `protobuf:"bytes,4,opt,name=ChangePrefix,proto3" json:"ChangePrefix,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Bookmark) Reset() {
	*x = Bookmark{}
	mi := &file_protos_messages_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Bookmark) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Bookmark) ProtoMessage() {}

func (x *Bookmark) ProtoReflect() protoreflect.Message {
	mi := &file_protos_messages_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Bookmark.ProtoReflect.Descriptor instead.
func (*Bookmark) Descriptor() ([]byte, []int) {
	return file_protos_messages_proto_rawDescGZIP(), []int{16}
}

func (x *Bookmark) GetBookmarkName() string {
	if x != nil {
		return x.BookmarkName
	}
	return ""
}

func (x *Bookmark) GetChangeID() int64 {
	if x != nil {
		return x.ChangeID
	}
	return 0
}

func (x *Bookmark) GetChangeName() string {
	if x != nil {
		return x.ChangeName
	}
	return ""
}

func (x *Bookmark) GetChangePrefix() string {
	if x != nil {
		return x.ChangePrefix
	}
	return ""
}

type ConflictsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Change        string                 `protobuf:"bytes,1,opt,name=Change,proto3" json:"Change,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConflictsRequest) Reset() {
	*x = ConflictsRequest{}
	mi := &file_protos_messages_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConflictsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConflictsRequest) ProtoMessage() {}

func (x *ConflictsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_protos_messages_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConflictsRequest.ProtoReflect.Descriptor instead.
func (*ConflictsRequest) Descriptor() ([]byte, []int) {
	return file_protos_messages_proto_rawDescGZIP(), []int{17}
}

func (x *ConflictsRequest) GetChange() string {
	if x != nil {
		return x.Change
	}
	return ""
}

type ConflictsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Conflicts     []string               `protobuf:"bytes,1,rep,name=Conflicts,proto3" json:"Conflicts,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConflictsResponse) Reset() {
	*x = ConflictsResponse{}
	mi := &file_protos_messages_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConflictsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConflictsResponse) ProtoMessage() {}

func (x *ConflictsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_protos_messages_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConflictsResponse.ProtoReflect.Descriptor instead.
func (*ConflictsResponse) Descriptor() ([]byte, []int) {
	return file_protos_messages_proto_rawDescGZIP(), []int{18}
}

func (x *ConflictsResponse) GetConflicts() []string {
	if x != nil {
		return x.Conflicts
	}
	return nil
}

var File_protos_messages_proto protoreflect.FileDescriptor

const file_protos_messages_proto_rawDesc = "" +
	"\n" +
	"\x15protos/messages.proto\x12\x06protos\x1a\x1fgoogle/protobuf/timestamp.proto\"\xa3\x02\n" +
	"\rHTTPSignature\x12\x1b\n" +
	"\tbody_hash\x18\x01 \x01(\fR\bbodyHash\x12!\n" +
	"\frequest_path\x18\x02 \x01(\tR\vrequestPath\x128\n" +
	"\ttimestamp\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\ttimestamp\x12\x1a\n" +
	"\busername\x18\x04 \x01(\tR\busername\x12\x1d\n" +
	"\n" +
	"machine_id\x18\x05 \x01(\tR\tmachineId\x12\x1d\n" +
	"\n" +
	"public_key\x18\x06 \x01(\fR\tpublicKey\x12\x16\n" +
	"\x06format\x18\a \x01(\tR\x06format\x12\x12\n" +
	"\x04blob\x18\b \x01(\fR\x04blob\x12\x12\n" +
	"\x04rest\x18\t \x01(\fR\x04rest\"?\n" +
	"\vInitRequest\x12\x12\n" +
	"\x04Name\x18\x01 \x01(\tR\x04Name\x12\x1c\n" +
	"\tBookmarks\x18\x02 \x03(\tR\tBookmarks\"&\n" +
	"\fInitResponse\x12\x16\n" +
	"\x06RepoID\x18\x01 \x01(\x05R\x06RepoID\"\xa2\x01\n" +
	"\fPushFileInfo\x12\x12\n" +
	"\x04Name\x18\x01 \x01(\tR\x04Name\x12#\n" +
	"\n" +
	"Executable\x18\x02 \x01(\bH\x00R\n" +
	"Executable\x88\x01\x01\x12 \n" +
	"\vContentHash\x18\x03 \x01(\fR\vContentHash\x12(\n" +
	"\x0fContainsContent\x18\x04 \x01(\bR\x0fContainsContentB\r\n" +
	"\v_Executable\";\n" +
	"\x17CheckFilesExistsRequest\x12 \n" +
	"\vContentHash\x18\x01 \x03(\fR\vContentHash\"2\n" +
	"\x18CheckFilesExistsResponse\x12\x16\n" +
	"\x06Exists\x18\x01 \x03(\bR\x06Exists\"\x87\x01\n" +
	"\x10NewChangeRequest\x12\x18\n" +
	"\aParents\x18\x01 \x03(\tR\aParents\x12%\n" +
	"\vdescription\x18\x02 \x01(\tH\x00R\vdescription\x88\x01\x01\x12\"\n" +
	"\fSetBookmarks\x18\x03 \x03(\tR\fSetBookmarksB\x0e\n" +
	"\f_description\"L\n" +
	"\x12SetBookmarkRequest\x12\x1a\n" +
	"\bBookmark\x18\x01 \x01(\tR\bBookmark\x12\x1a\n" +
	"\bChangeId\x18\x02 \x01(\x03R\bChangeId\"/\n" +
	"\x11NewChangeResponse\x12\x1a\n" +
	"\bChangeId\x18\x01 \x01(\x03R\bChangeId\"-\n" +
	"\x0fCheckoutRequest\x12\x1a\n" +
	"\bChangeId\x18\x01 \x01(\x03R\bChangeId\"R\n" +
	"\n" +
	"LogRequest\x12\x12\n" +
	"\x04Head\x18\x01 \x01(\tR\x04Head\x12\x14\n" +
	"\x05Limit\x18\x02 \x01(\x05R\x05Limit\x12\x1a\n" +
	"\bTimeZone\x18\x03 \x01(\tR\bTimeZone\"\x1f\n" +
	"\vLogResponse\x12\x10\n" +
	"\x03Log\x18\x01 \x01(\tR\x03Log\"W\n" +
	"\x11FindChangeRequest\x12\x12\n" +
	"\x04Name\x18\x01 \x01(\tR\x04Name\x12.\n" +
	"\x12IncludeDescription\x18\x02 \x01(\bR\x12IncludeDescription\"g\n" +
	"\x12FindChangeResponse\x12\x1a\n" +
	"\bChangeId\x18\x01 \x01(\x03R\bChangeId\x12%\n" +
	"\vDescription\x18\x02 \x01(\tH\x00R\vDescription\x88\x01\x01B\x0e\n" +
	"\f_Description\"K\n" +
	"\x0fDescribeRequest\x12\x16\n" +
	"\x06Change\x18\x01 \x01(\tR\x06Change\x12 \n" +
	"\vDescription\x18\x02 \x01(\tR\vDescription\"G\n" +
	"\x15ListBookmarksResponse\x12.\n" +
	"\tBookmarks\x18\x01 \x03(\v2\x10.protos.BookmarkR\tBookmarks\"\x8e\x01\n" +
	"\bBookmark\x12\"\n" +
	"\fBookmarkName\x18\x01 \x01(\tR\fBookmarkName\x12\x1a\n" +
	"\bChangeID\x18\x02 \x01(\x03R\bChangeID\x12\x1e\n" +
	"\n" +
	"ChangeName\x18\x03 \x01(\tR\n" +
	"ChangeName\x12\"\n" +
	"\fChangePrefix\x18\x04 \x01(\tR\fChangePrefix\"*\n" +
	"\x10ConflictsRequest\x12\x16\n" +
	"\x06Change\x18\x01 \x01(\tR\x06Change\"1\n" +
	"\x11ConflictsResponse\x12\x1c\n" +
	"\tConflicts\x18\x01 \x03(\tR\tConflictsB&Z$github.com/tsukinoko-kun/pogo/protosb\x06proto3"

var (
	file_protos_messages_proto_rawDescOnce sync.Once
	file_protos_messages_proto_rawDescData []byte
)

func file_protos_messages_proto_rawDescGZIP() []byte {
	file_protos_messages_proto_rawDescOnce.Do(func() {
		file_protos_messages_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_protos_messages_proto_rawDesc), len(file_protos_messages_proto_rawDesc)))
	})
	return file_protos_messages_proto_rawDescData
}

var file_protos_messages_proto_msgTypes = make([]protoimpl.MessageInfo, 19)
var file_protos_messages_proto_goTypes = []any{
	(*HTTPSignature)(nil),            // 0: protos.HTTPSignature
	(*InitRequest)(nil),              // 1: protos.InitRequest
	(*InitResponse)(nil),             // 2: protos.InitResponse
	(*PushFileInfo)(nil),             // 3: protos.PushFileInfo
	(*CheckFilesExistsRequest)(nil),  // 4: protos.CheckFilesExistsRequest
	(*CheckFilesExistsResponse)(nil), // 5: protos.CheckFilesExistsResponse
	(*NewChangeRequest)(nil),         // 6: protos.NewChangeRequest
	(*SetBookmarkRequest)(nil),       // 7: protos.SetBookmarkRequest
	(*NewChangeResponse)(nil),        // 8: protos.NewChangeResponse
	(*CheckoutRequest)(nil),          // 9: protos.CheckoutRequest
	(*LogRequest)(nil),               // 10: protos.LogRequest
	(*LogResponse)(nil),              // 11: protos.LogResponse
	(*FindChangeRequest)(nil),        // 12: protos.FindChangeRequest
	(*FindChangeResponse)(nil),       // 13: protos.FindChangeResponse
	(*DescribeRequest)(nil),          // 14: protos.DescribeRequest
	(*ListBookmarksResponse)(nil),    // 15: protos.ListBookmarksResponse
	(*Bookmark)(nil),                 // 16: protos.Bookmark
	(*ConflictsRequest)(nil),         // 17: protos.ConflictsRequest
	(*ConflictsResponse)(nil),        // 18: protos.ConflictsResponse
	(*timestamppb.Timestamp)(nil),    // 19: google.protobuf.Timestamp
}
var file_protos_messages_proto_depIdxs = []int32{
	19, // 0: protos.HTTPSignature.timestamp:type_name -> google.protobuf.Timestamp
	16, // 1: protos.ListBookmarksResponse.Bookmarks:type_name -> protos.Bookmark
	2,  // [2:2] is the sub-list for method output_type
	2,  // [2:2] is the sub-list for method input_type
	2,  // [2:2] is the sub-list for extension type_name
	2,  // [2:2] is the sub-list for extension extendee
	0,  // [0:2] is the sub-list for field type_name
}

func init() { file_protos_messages_proto_init() }
func file_protos_messages_proto_init() {
	if File_protos_messages_proto != nil {
		return
	}
	file_protos_messages_proto_msgTypes[3].OneofWrappers = []any{}
	file_protos_messages_proto_msgTypes[6].OneofWrappers = []any{}
	file_protos_messages_proto_msgTypes[13].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_protos_messages_proto_rawDesc), len(file_protos_messages_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   19,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_protos_messages_proto_goTypes,
		DependencyIndexes: file_protos_messages_proto_depIdxs,
		MessageInfos:      file_protos_messages_proto_msgTypes,
	}.Build()
	File_protos_messages_proto = out.File
	file_protos_messages_proto_goTypes = nil
	file_protos_messages_proto_depIdxs = nil
}
